name: CI for Ubuntu

on: push

jobs:

  linux:
    strategy:
      fail-fast: false
      matrix:
        os: ubuntu-latest
        inchs: [ 0, 1 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: Install cpanm
        run: |
          sudo apt-get update
          sudo apt-get install cpanminus
      - name: Install HarfBuzz
        run: |
          sudo apt-get install libharfbuzz-dev
          pkg-config --libs harfbuzz
      - name: Install Dependencies
        run: cpanm --installdeps --notest .  || cat /Users/runner/.cpanm/build.log
      - name: Build
        env:
          INCHS: ${{ matrix.inchs }}
        run: |
          perl Makefile.PL
          make
      - name: Run Tests
        run: make test
